### ISSUE TITLE
No Plugin Compatibility Information

### ISSUE THREAD

**Issue by justinlosh** [akhoury/nodebb-plugin-mailchimp#2]
When you attempt to install the plugin through the ACP, you get the following error:

No Compatibility Information Found
This plugin did not specify a specific version for installation given your NodeBB version. Full compatibility cannot be guaranteed, and may cause your NodeBB to no longer start properly.

Note: I would find this plugin extremely useful, it would be great if it was updated.

**Comment by akhoury** [comment]
done. Published nodebb-plugin-mailchimp@0.3.0 - I don't have MailChimp Account anymore, I tested it with a fake Key and it does not crash anymore. 

To be honest I am not too sure how useful this plugin is now, since in NodeBB Admin panel > Users you can just download a CSV file with all of your users with their emails and upload them to MailChimp

**Comment by akhoury** [comment]
actually nodebb-plugin-mailchimp@0.3.1

**Comment by justinlosh** [comment]
Awesome! Thanks!
